name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 1️⃣ Análisis estático (TFLint)
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint Init
        run: tflint --init

      - name: TFLint Run
        run: tflint

      # 2️⃣ Análisis de seguridad (Checkov)
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .

      # 3️⃣ Validación Terraform
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # 4️⃣ Políticas OPA
      - name: Run OPA Policies
        uses: open-policy-agent/opa-github-actions@v2
        with:
          policy-path: policies